# Manipulating Tensors

In deep learning data represents in tensors. when the model is training it will perform a series of operations on tensor to find the patterns in the data.

ex:

Addition

Subtraction

Multiplication(element-wise)

Division

Matrix Multiplication(Most Useful)

In [1]:
# creating a tensor to perform the math operations
import torch
tensor = torch.tensor(2)
print('tensor: ', tensor)

tensor:  tensor(2)


In [2]:
# Addition
print('adding 5 to tensor: ', tensor+5)
print('tensor:', tensor)
# for one tensor it will be easy just it add 5 to 2 5+2=7
# if we see it still 2 to replicate in tensor we have to assign to the variable
tensor = tensor + 5
print('tensor:', tensor)

vector = torch.tensor([1, 2, 5,65,8])
vector = vector + 5
print('adding 5 to every element in a vector: ', vector)

'''
The addition happend element vector: [1, 2, 5,65,8]
1 + 5 = 6
2 + 5 = 7
5 + 5 = 10
65 + 5 = 70
8 + 5 = 13
result of tensor = [ 6,  7, 10, 70, 13]
every math operation will perform same like this except matrix multiplication
'''

adding 5 to tensor:  tensor(7)
tensor: tensor(2)
tensor: tensor(7)
adding 5 to every element in a vector:  tensor([ 6,  7, 10, 70, 13])


'\nThe addition happend element vector: [1, 2, 5,65,8]\n1 + 5 = 6\n2 + 5 = 7\n5 + 5 = 10\n65 + 5 = 70\n8 + 5 = 13\nresult of tensor = [ 6,  7, 10, 70, 13]\nevery math operation will perform same like this except matrix multiplication\n'

In [3]:
# Subtraction
print('subtracting 5 to tensor: ', tensor - 5)
print('tensor:', tensor)
# for one tensor it will be easy just it add 5 to 2 5+2=7
# if we see it still 2 to replicate in tensor we have to assign to the variable
tensor = tensor - 5
print('tensor:', tensor)

vector = torch.tensor([1, 2, 5,65,8])
vector = vector - 5
print('subtracting 5 to every element in a vector: ', vector)

subtracting 5 to tensor:  tensor(2)
tensor: tensor(7)
tensor: tensor(2)
subtracting 5 to every element in a vector:  tensor([-4, -3,  0, 60,  3])


In [4]:
# Subtraction
print('multiplication 5 to tensor: ', tensor * 5)
print('tensor:', tensor)
# for one tensor it will be easy just it add 5 to 2 5+2=7
# if we see it still 2 to replicate in tensor we have to assign to the variable
tensor = tensor * 5
print('tensor:', tensor)

vector = torch.tensor([1, 2, 5,65,8])
vector = vector * 5
print('multiplication 5 to every element in a vector: ', vector)

multiplication 5 to tensor:  tensor(10)
tensor: tensor(2)
tensor: tensor(10)
multiplication 5 to every element in a vector:  tensor([  5,  10,  25, 325,  40])


In [5]:
# Division
print('division 5 to tensor: ', tensor / 5)
print('tensor:', tensor)
# for one tensor it will be easy just it add 5 to 2 5+2=7
# if we see it still 2 to replicate in tensor we have to assign to the variable
tensor = tensor / 5
print('tensor:', tensor)

vector = torch.tensor([1, 2, 5,65,8])
vector = vector / 5
print('division 5 to every element in a vector: ', vector)

division 5 to tensor:  tensor(2.)
tensor: tensor(10)
tensor: tensor(2.)
division 5 to every element in a vector:  tensor([ 0.2000,  0.4000,  1.0000, 13.0000,  1.6000])


# Matrix Multiplication

One of the most common operation used in maching learning and deep learning.matrix multiplication is a core operation in deep learning that enables efficient computation of complex mathematical transformations, making it essential for training and deploying neural networks.

examples of matix multiplcation used in:

1) **Fully Connected Layers (Dense Layers):** When inputs from one layer are multiplied by weights and summed, this operation can be efficiently represented as a matrix multiplication.

2) **Convolutional Layers:** These convolution operations can be implemented as a series of matrix multiplications, where the input data and filters (kernels) are represented as matrices and convolutions are performed using matrix multiplication.

3) **Recurrent Neural Networks (RNNs):** Matrix multiplication is used to update and propagate the hidden state through time steps, making RNNs efficient for sequence modeling tasks such as natural language processing (NLP) and time series prediction.

4) **Batch Processing:** Matrix multiplication allows for parallel processing of these batches, which accelerates training and inference on modern hardware such as GPUs and TPUs.

5) Regularization: This can be implemented efficiently using matrix multiplication by scaling the activations of neurons appropriately.

To get better understading of matrix multiplication do visit the below website:
https://www.mathsisfun.com/algebra/matrix-multiplying.html



In [6]:
# Matix Muliplication
matrix_a = torch.tensor([[2, 5, 6],
                         [8, 10, 9]])
print('matrix a with 3 rows and 2 columns: ', matrix_a)

matrix a with 3 rows and 2 columns:  tensor([[ 2,  5,  6],
        [ 8, 10,  9]])


In [7]:
matrix_b = torch.tensor([[6, 4, 4],
                         [6, 5, 9]])
print('matrix b with 3 rows and 2 columns: ', matrix_b)

matrix b with 3 rows and 2 columns:  tensor([[6, 4, 4],
        [6, 5, 9]])


In [8]:
print("Size of Matrix A: ", matrix_a.shape)
print("Size of Matrix B: ", matrix_b.shape)

Size of Matrix A:  torch.Size([2, 3])
Size of Matrix B:  torch.Size([2, 3])


In [9]:
print("The size of Matrix a and b are same 2 rows 3 columns")
# lets do matrix multiplication using torch.matmul(a, b)
torch.matmul(matrix_a, matrix_b)

The size of Matrix a and b are same 2 rows 3 columns


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [10]:
# We got error the 1st rule of matmul the shapes of the matrices are not to bee same

'''
ex: matrix_a: [2, 3] and matix_b: [2, 3] -> Get Error
The shapes of the matrices need to be vice versa
matrix_a: [2, 3] and matrix b need to be [3, 2] lets try
'''

# In PyTorch we have transpose() function to shift row into columns and vice versa
# torch.transpose(matrix, dim0, dim1)
print('Transpose the matrix_b: ', torch.transpose(matrix_b, 1, 0)) # i am shifting 1 column to row and 0 row to column
print('Another way to do transpose: ', matrix_b.T)

Transpose the matrix_b:  tensor([[6, 6],
        [4, 5],
        [4, 9]])
Another way to do transpose:  tensor([[6, 6],
        [4, 5],
        [4, 9]])


In [11]:
matrix_b = matrix_b.T
matrix_b

tensor([[6, 6],
        [4, 5],
        [4, 9]])

In [12]:
# mat multiplication
mat_mul_a_b = torch.matmul(matrix_a, matrix_b)
mat_mul_a_b

tensor([[ 56,  91],
        [124, 179]])

In [13]:
# Debugging How Matrix Multiplication is happening
print('matrix a: ', matrix_a)
print('matrix_b: ', matrix_b)

matrix a:  tensor([[ 2,  5,  6],
        [ 8, 10,  9]])
matrix_b:  tensor([[6, 6],
        [4, 5],
        [4, 9]])


In [14]:
# firs it will take the 1 row and all columns
print('matrix_a 1row and all columns: ', matrix_a[0])
print('marix_b all rows 1st column: ', matrix_b[:, 0])
mat_mul=[]
c = 0
while c != 2:
  mat_count = 0
  for val_a, val_b in zip(matrix_a[0], matrix_b[:, c]):
    print(f'multiplying {val_a} and {val_b}: ', (val_a * val_b).item())
    mat_count += (val_a * val_b)
  mat_mul.append(mat_count.item())
  c += 1
print(mat_mul)

matrix_a 1row and all columns:  tensor([2, 5, 6])
marix_b all rows 1st column:  tensor([6, 4, 4])
multiplying 2 and 6:  12
multiplying 5 and 4:  20
multiplying 6 and 4:  24
multiplying 2 and 6:  12
multiplying 5 and 5:  25
multiplying 6 and 9:  54
[56, 91]


In [15]:
print('matrix_a 2row and all columns: ', matrix_a[1])
print('marix_b all rows all column: ', matrix_b[:, :])
c = 0
while c != 2:
  mat_count = 0
  for val_a, val_b in zip(matrix_a[1], matrix_b[:, c]):
    print(f'multiplying {val_a} and {val_b}: ', (val_a * val_b).item())
    mat_count += (val_a * val_b)
  mat_mul.append(mat_count.item())
  c += 1
print(mat_mul)

matrix_a 2row and all columns:  tensor([ 8, 10,  9])
marix_b all rows all column:  tensor([[6, 6],
        [4, 5],
        [4, 9]])
multiplying 8 and 6:  48
multiplying 10 and 4:  40
multiplying 9 and 4:  36
multiplying 8 and 6:  48
multiplying 10 and 5:  50
multiplying 9 and 9:  81
[56, 91, 124, 179]


In [16]:
print('Mat multiplication of matrix_a and matrix_b with torhc.matmul: ', mat_mul_a_b)
print('Mat multiplication of matrix_a and matrix_b with python code: ', mat_mul)

Mat multiplication of matrix_a and matrix_b with torhc.matmul:  tensor([[ 56,  91],
        [124, 179]])
Mat multiplication of matrix_a and matrix_b with python code:  [56, 91, 124, 179]


In [17]:
# reshaping mat mul
# first we need to convert python list to numpy array
import numpy as np
mat_mul_array = np.array(mat_mul)
print('mat_mul_array: ', mat_mul_array, 'type: ', type(mat_mul_array))
mat_mul_tensor = torch.from_numpy(mat_mul_array)
print('mat_mul_tensor: ', mat_mul_tensor, 'type: ', type(mat_mul_tensor))

# reshaping the tensor to 2 * 2 Matrix
mat_mul_tensor = mat_mul_tensor.reshape((2, 2))
print(mat_mul_tensor)

mat_mul_array:  [ 56  91 124 179] type:  <class 'numpy.ndarray'>
mat_mul_tensor:  tensor([ 56,  91, 124, 179]) type:  <class 'torch.Tensor'>
tensor([[ 56,  91],
        [124, 179]])


In [18]:
print('Mat multiplication of matrix_a and matrix_b with torhc.matmul: ', mat_mul_a_b)
print('Mat multiplication of matrix_a and matrix_b with python code: ', mat_mul_tensor)

Mat multiplication of matrix_a and matrix_b with torhc.matmul:  tensor([[ 56,  91],
        [124, 179]])
Mat multiplication of matrix_a and matrix_b with python code:  tensor([[ 56,  91],
        [124, 179]])


# sample shapes for matrix multiplication
*----A----*|*----B----*|*----works----*|*---ouput_shape----*

(3, 2)      (3, 2)         won't work         None

(3, 2)      (2, 3)          works            (3, 3)

(8, 8)      (8, 8)          works            (8, 8)

(8, 4)      (4, 8)          works            (8, 8)

(9, 5)      (5, 9)         works             (9, 9)

# Note: Better way to find the output of matrix multiplication is matrix_a no of rows, and matrix_b no of columns: output_shape(matrix_a_rows, matrix_b_columns)

visite: http://matrixmultiplication.xyz/ to visulize how the matrix multiplication works

In [19]:
_8_a = torch.arange(1, 46).reshape((9, 5))
_8_b = torch.arange(46, 91).reshape((5, 9))
torch.matmul(_8_b, _8_a).shape

torch.Size([5, 5])

In [20]:
# other ways to do matrix multiplication

# torhc.mm() short from of torch.matmul()

In [21]:
# finding the min,max,mean and sum in tensor
tensor = torch.randint(low=1, high=100, size=(5, 6))
print('tensor: ', tensor)

tensor:  tensor([[65, 61, 47,  2, 77,  7],
        [ 7, 26, 81, 61, 93, 63],
        [69, 41, 12,  2,  2, 45],
        [84, 66, 36, 80, 47, 30],
        [12, 63,  6, 60, 65, 77]])


In [22]:
print("Max number in tensor: ", tensor.max())
print("Min number in tensor: ", tensor.min())
print("Mean of tensor: ", tensor.type(torch.float32).mean()) # to find mean the data of torch need to be float or complex number
print("sum of the tensor: ", tensor.sum())

Max number in tensor:  tensor(93)
Min number in tensor:  tensor(2)
Mean of tensor:  tensor(46.2333)
sum of the tensor:  tensor(1387)


In [23]:
print('tensor:' ,tensor)
print('tensor data type: ', tensor.dtype)

tensor: tensor([[65, 61, 47,  2, 77,  7],
        [ 7, 26, 81, 61, 93, 63],
        [69, 41, 12,  2,  2, 45],
        [84, 66, 36, 80, 47, 30],
        [12, 63,  6, 60, 65, 77]])
tensor data type:  torch.int64


In [24]:
# The tensor data type is int64
tensor = tensor.type(torch.float32)
tensor

tensor([[65., 61., 47.,  2., 77.,  7.],
        [ 7., 26., 81., 61., 93., 63.],
        [69., 41., 12.,  2.,  2., 45.],
        [84., 66., 36., 80., 47., 30.],
        [12., 63.,  6., 60., 65., 77.]])

In [25]:
print("tensore data type: ", tensor.dtype)

tensore data type:  torch.float32


# Reshaping, stacking, squeezing and unsqueezing
Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors

In [26]:
# reshaping the tensor
tensor = torch.arange(10)
tensor, tensor.size()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [27]:
# the size of the tensor is 10 it contains 10 values
print('Reshaping tensor into 5*2', tensor.reshape((5, 2))) # vice versa

Reshaping tensor into 5*2 tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [28]:
print('Reshaping tensor into 6 * 2', tensor.reshape((6, 2)))

RuntimeError: shape '[6, 2]' is invalid for input of size 10

In [29]:
"""
Above we got the error because the size of the tensor is 10
to convert into 6 * 2 we need tensor of 12 value .
Note: Make sure the size need to compatable to resize the tensor
"""

'\nAbove we got the error because the size of the tensor is 10\nto convert into 6 * 2 we need tensor of 12 value .\nNote: Make sure the size need to compatable to resize the tensor\n'

In [30]:
# torch.view() its same like reshape
tensor = torch.arange(12).reshape((2, 6))
tensor, tensor.size()

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 torch.Size([2, 6]))

In [31]:
tensor_view = tensor.view((6, 2))
tensor_view

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [32]:
print('tensor: ', tensor)
print('tensor_view: ', tensor_view)

tensor:  tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor_view:  tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


In [33]:
# torch.stack(): method will concatenate the tensors togethe will new dimension every time
# make sure the sizes of the tensor a and b need to be same
tensor1 = torch.arange(1, 10)
tensor2 = torch.arange(11, 20)
print('tensor1 : ', tensor1)
print('tensor2: ', tensor2)

tensor1 :  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor2:  tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


In [34]:
# concatenating the tensor1 and tensor2
concatenate12 = torch.stack((tensor1, tensor2))
print('concatenated 1 and 2: ', concatenate12)
print('shape of the concatenate12: ', concatenate12.shape)

concatenated 1 and 2:  tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 12, 13, 14, 15, 16, 17, 18, 19]])
shape of the concatenate12:  torch.Size([2, 9])


In [35]:
print('dimension of the concatenate12: ', concatenate12.ndim)

dimension of the concatenate12:  2


In [36]:
# adding one more tensor to
tensor3 = torch.arange(21, 30)
tensor3

tensor([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
concatenate123 = torch.stack((tensor1, tensor2, tensor3))
print('concatenated 1 and 2: ', concatenate123)
print('shape of the concatenate123: ', concatenate123.shape)

concatenated 1 and 2:  tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 12, 13, 14, 15, 16, 17, 18, 19],
        [21, 22, 23, 24, 25, 26, 27, 28, 29]])
shape of the concatenate123:  torch.Size([3, 9])


In [38]:
# we can add as many as we need
tensor4 = tensor1.reshape(3, 3)
tensor5 = tensor2.reshape(3, 3)
tensor6 = tensor3.reshape(3, 3)
print('tensor4: ', tensor4)
print('tensor5: ', tensor5)
print('tensor6: ', tensor6)

tensor4:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor5:  tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor6:  tensor([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]])


In [39]:
concatenate456 = torch.stack((tensor4, tensor5, tensor6))
print('concatenated 1 and 2: ', concatenate456)
print('shape of the concatenate456: ', concatenate456.shape)

concatenated 1 and 2:  tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])
shape of the concatenate456:  torch.Size([3, 3, 3])


In [40]:
# torch.sqeeze() It squeezes (removes) the size 1 and returns a tensor with all other dimensions of the input tensor.

tensor = torch.tensor([[1, 2, 3, 4, 5]])
print(tensor)
print(tensor.ndim)

tensor([[1, 2, 3, 4, 5]])
2


In [41]:
# the tensor is 2 dimensiona
# to remove a dimension from the tensor use squeeze()
# removed dimension
tensor = torch.squeeze(tensor)
tensor, tensor.ndim

(tensor([1, 2, 3, 4, 5]), 1)

In [42]:
tensor = torch.squeeze(tensor)
tensor, tensor.ndim

(tensor([1, 2, 3, 4, 5]), 1)

In [43]:
# torch.unsqeeze(): it add the dimension to tensor
tensor, tensor.ndim

(tensor([1, 2, 3, 4, 5]), 1)

In [44]:
tensor = tensor.unsqueeze(dim=1)
tensor, tensor.ndim

(tensor([[1],
         [2],
         [3],
         [4],
         [5]]),
 2)

In [45]:
tensor = tensor.unsqueeze(dim=1)
tensor, tensor.ndim

(tensor([[[1]],
 
         [[2]],
 
         [[3]],
 
         [[4]],
 
         [[5]]]),
 3)

# Indexing (selecting the data from tensor)

In [46]:
scalar = torch.arange(1, 10)
print("scalar: ", scalar)

scalar:  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [47]:
# just like python3 we can using indexing to access the elements
scalar[0].item()

1

In [48]:
scalar[5].item()

6

In [49]:
vector = torch.arange(1, 17).reshape((4, 4))
vector, vector.shape, vector.ndim

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),
 torch.Size([4, 4]),
 2)

In [50]:
# vector is 4 * 4 metrics
print('access the 1st row 3rd column value: ', vector[0, 2].item())
print('access the 3rd row 2nd column value: ', vector[2, 1].item())

access the 1st row 3rd column value:  3
access the 3rd row 2nd column value:  10


In [51]:
# access the all rows from 1st column
print('all rows 1st column: ', vector[:, 0])

all rows 1st column:  tensor([ 1,  5,  9, 13])


In [52]:
print('all columns of last row: ', vector[-1, :])

all columns of last row:  tensor([13, 14, 15, 16])
