In Deep learning , data will be (image, audio,video, text etc) data will present in a tensor.

A lot's of operations will happen on tensor to represent a patter from the
input data.

so lets see some manipulation techniques using torch.

In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


In [2]:
# addition
# element wise addition
tensor = torch.Tensor([1, 5, 7, 10, 11])
print("tensor: ", tensor)

tensor:  tensor([ 1.,  5.,  7., 10., 11.])


In [3]:
print("Before adding the value to tensor: ", tensor)
print("after adding a element to the tensor: ", tensor + 10)
print("tensor: ", tensor)

Before adding the value to tensor:  tensor([ 1.,  5.,  7., 10., 11.])
after adding a element to the tensor:  tensor([11., 15., 17., 20., 21.])
tensor:  tensor([ 1.,  5.,  7., 10., 11.])


In [4]:
"""
Have you observed the last output of the tensor is till same. because the will added the value
but we didn't assign to the variable.
"""
tensor = tensor + 10
print("tensor: ", tensor)

tensor:  tensor([11., 15., 17., 20., 21.])


In [5]:
# subtraction
print("Before adding the value to tensor: ", tensor)
print("after adding a element to the tensor: ", tensor - 10)
tensor = tensor - 10
print("tensor: ", tensor)

Before adding the value to tensor:  tensor([11., 15., 17., 20., 21.])
after adding a element to the tensor:  tensor([ 1.,  5.,  7., 10., 11.])
tensor:  tensor([ 1.,  5.,  7., 10., 11.])


In [6]:
# multiplication
print("Before adding the value to tensor: ", tensor)
print("after adding a element to the tensor: ", tensor * 10)
tensor = tensor * 10
print("tensor: ", tensor)

Before adding the value to tensor:  tensor([ 1.,  5.,  7., 10., 11.])
after adding a element to the tensor:  tensor([ 10.,  50.,  70., 100., 110.])
tensor:  tensor([ 10.,  50.,  70., 100., 110.])


In [7]:
# the most important operation, matrix multiplication
# One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.
# there are different type of function to do matrix multiplication

# 1) torch.matmul(): https://pytorch.org/docs/stable/generated/torch.matmul.html

tensor_a = torch.Tensor([[1 , 2, 3],
                         [4, 5, 6],
                         [8, 7, 9]])
tensor_b = torch.Tensor([[1 , 2, 3],
                         [4, 5, 6],
                         [8, 7, 9]])
print("tensor_a: ", tensor_a)
print()
print("tensor_b: ", tensor_b)

tensor_a:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [8., 7., 9.]])

tensor_b:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [8., 7., 9.]])


In [8]:
# lets check the shape of the matrices
print("tensor_a shape: ", tensor_a.shape, "tensor_b: ", tensor_b.shape)

tensor_a shape:  torch.Size([3, 3]) tensor_b:  torch.Size([3, 3])


In [9]:
# the shape are the same if we do the matmult we won't get any issues
torch.matmul(tensor_a, tensor_b)

tensor([[ 33.,  33.,  42.],
        [ 72.,  75.,  96.],
        [108., 114., 147.]])

In [10]:
#ex: 2
tensor_a = torch.Tensor([[1 , 2],
                         [4, 5],
                         [8, 7]])
tensor_b = torch.Tensor([[1 , 2],
                         [4, 5],
                         [8, 7]])
print("tensor_a: ", tensor_a)
print()
print("tensor_b: ", tensor_b)

tensor_a:  tensor([[1., 2.],
        [4., 5.],
        [8., 7.]])

tensor_b:  tensor([[1., 2.],
        [4., 5.],
        [8., 7.]])


In [11]:
# lets check the shape of the matrices
print("tensor_a shape: ", tensor_a.shape, "tensor_b: ", tensor_b.shape)

tensor_a shape:  torch.Size([3, 2]) tensor_b:  torch.Size([3, 2])


In [12]:
# if you observed the shapes of the both tensors are the same, let's do matmul
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [13]:
# we got an error, when have the shapes like the row and columns did match
# we need to transpose the rows and columns using tesor.T
tensor_b = tensor_b.T
torch.matmul(tensor_a, tensor_b)

tensor([[  5.,  14.,  22.],
        [ 14.,  41.,  67.],
        [ 22.,  67., 113.]])

In [14]:
# now you wont get any error to under stood how matmult happend when row and columns are not same
# please check out: http://matrixmultiplication.xyz/

In [15]:
# other useful tensor operations
print('tensor_a: ', tensor_a)
sum = torch.sum(tensor_a)
print("tensor_a sum: ", sum)
print('we got 27 because: 1+2+4+5+8+7=27')
# if you want you can also do sum based on axis4
sum_x = torch.sum(tensor_a, dim=0)
print("tensor_a sum: ", sum_x)

tensor_a:  tensor([[1., 2.],
        [4., 5.],
        [8., 7.]])
tensor_a sum:  tensor(27.)
we got 27 because: 1+2+4+5+8+7=27
tensor_a sum:  tensor([13., 14.])


In [19]:
# getting the maximum value, torch.max return the value and its index
value, index = torch.max(tensor_a, dim=0)
print(value, index)
# getting the minimum value, torch.max return the value and its index
value, index = torch.min(tensor_a, dim=0)
print(value, index)

tensor([8., 7.]) tensor([2, 2])
tensor([1., 2.]) tensor([0, 0])


In [21]:
# we have a another function to get max and min value from tensor torch.argmax and torch.argmin it only return value not indexes
max_value = torch.argmax(tensor_a)
min_value=torch.argmin(tensor_a)
print("max_value: ", max_value, "min_value: ", min_value)

max_value:  tensor(4) min_value:  tensor(0)


In [23]:
# we can also do sorting using torch.sort, which will return the sorted_array and indexes
sorted_arr, indexes = torch.sort(tensor_a, dim=1)
print("sorted_arr: ", sorted_arr)

sorted_arr:  tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])
