# Tensor Indexing

In [46]:
import torch
torch.__version__

'2.2.1+cu121'

In [47]:
rows = 5
columns = 10
tensor = torch.rand((rows, columns))

In [48]:
tensor

tensor([[0.0988, 0.7055, 0.7416, 0.4147, 0.1640, 0.7897, 0.3514, 0.4658, 0.5390,
         0.5835],
        [0.5511, 0.4439, 0.2630, 0.4850, 0.8437, 0.6115, 0.8746, 0.9514, 0.3684,
         0.1987],
        [0.3837, 0.5136, 0.0127, 0.4076, 0.8824, 0.6937, 0.4816, 0.2131, 0.1585,
         0.0011],
        [0.1989, 0.2132, 0.7584, 0.5742, 0.2353, 0.1452, 0.0763, 0.8331, 0.1354,
         0.5476],
        [0.5038, 0.2040, 0.0172, 0.0233, 0.5552, 0.7317, 0.8823, 0.3144, 0.2838,
         0.4621]])

In [49]:
tensor.shape

torch.Size([5, 10])

In [50]:
tensor[0] # accessed first row

tensor([0.0988, 0.7055, 0.7416, 0.4147, 0.1640, 0.7897, 0.3514, 0.4658, 0.5390,
        0.5835])

In [51]:
tensor[0].shape

torch.Size([10])

In [52]:
# if you want to access the first row all columns
tensor[0, :] # [0, :] 0 row, : all columns

tensor([0.0988, 0.7055, 0.7416, 0.4147, 0.1640, 0.7897, 0.3514, 0.4658, 0.5390,
        0.5835])

In [53]:
# if you want to only access the all 1 rows 1 colum
tensor[:, 0]  # :=all rows, 0=column

tensor([0.0988, 0.5511, 0.3837, 0.1989, 0.5038])

In [54]:
# if you want select all values use=:, default it takes 0 and len-1.
# or either you can use start:end(length-1)

In [55]:
# Accessing multiple values in a tensor giving the list of indices
tensor1 = torch.arange(10)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
indices = [1, 5, 2] # list of indices to get values
tensor1[indices]

tensor([1, 5, 2])

In [57]:
# More advanced indexing
# boolen index

tensor2 = torch.arange(20)

In [58]:
tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [59]:
# lets get the values which are less than 5 and greater than 15.
# output need to be: 1, 2, 3, 4, 16, 17, 18, 19
# writing the condition use the ()
tensor2[(tensor2 < 5) | (tensor2 > 15)]

tensor([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [60]:
# | or , & and
tensor2[(tensor2 > 5) & (tensor2 <15)]

tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
# values that divided by 2 tensor.remainder(value)
tensor2[tensor2.remainder(2) == 0]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
# torch.where(condition, input, otherwise)
torch.where(tensor2 > 10, tensor2, tensor2**2)
# if the value is > 10 i am sqaring the values, otherwise return value

tensor([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100,  11,  12,  13,
         14,  15,  16,  17,  18,  19])

In [63]:
tensor3 = torch.tensor([1, 5, 5, 8, 7, 6, 7, 1])

In [64]:
# tensor3 have the duplicate using tensor.uniques()
tensor3.unique()

tensor([1, 5, 6, 7, 8])

In [65]:
# tensor.ndimension() will return the how many dimension tensor
tensor3.ndimension()

1

In [66]:
# lets do some value manipulation using the indexing techniques
tensor4 = torch.ones((5, 5))
tensor4

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [67]:
tensor5 = tensor4.clone() # copying the tensor using tesor.clone()
tensor5[0, 4] = 10 # replacing the value 1 to 10, at the 0 row 5 column
tensor5


tensor([[ 1.,  1.,  1.,  1., 10.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])

In [68]:
tensor5[:, 0] = 7 # replacing the 1 columns all rows with 7
tensor5

tensor([[ 7.,  1.,  1.,  1., 10.],
        [ 7.,  1.,  1.,  1.,  1.],
        [ 7.,  1.,  1.,  1.,  1.],
        [ 7.,  1.,  1.,  1.,  1.],
        [ 7.,  1.,  1.,  1.,  1.]])

In [69]:
tensor5[3, :] = 45
tensor5

tensor([[ 7.,  1.,  1.,  1., 10.],
        [ 7.,  1.,  1.,  1.,  1.],
        [ 7.,  1.,  1.,  1.,  1.],
        [45., 45., 45., 45., 45.],
        [ 7.,  1.,  1.,  1.,  1.]])

In [70]:
torch.where(tensor5==45, tensor5, 0) # replacing the 0 where the value is not 45

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [45., 45., 45., 45., 45.],
        [ 0.,  0.,  0.,  0.,  0.]])

# Tensor Reshaping

In [71]:
tensor = torch.rand(9)
tensor

tensor([0.5321, 0.2675, 0.9010, 0.2575, 0.5148, 0.5502, 0.7392, 0.6158, 0.8688])

In [72]:
# reshape into 3 * 3 metrics, make sure to assing variable it wont reshape in tensor
tensor = tensor.view(3, 3)
tensor

tensor([[0.5321, 0.2675, 0.9010],
        [0.2575, 0.5148, 0.5502],
        [0.7392, 0.6158, 0.8688]])

In [73]:
tensor1 = torch.rand(10)
tensor1

tensor([0.8761, 0.1116, 0.8562, 0.5856, 0.0437, 0.5351, 0.1953, 0.8731, 0.2051,
        0.4115])

In [74]:
tensor1 = tensor1.view(5, 2)
tensor1

tensor([[0.8761, 0.1116],
        [0.8562, 0.5856],
        [0.0437, 0.5351],
        [0.1953, 0.8731],
        [0.2051, 0.4115]])

In [75]:
tensor2 = torch.rand(10)
tensor2

tensor([0.5251, 0.3824, 0.8677, 0.0751, 0.2201, 0.7815, 0.6547, 0.1788, 0.1465,
        0.1043])

In [76]:
tensor2 = tensor2.view(2, 5)
tensor2

tensor([[0.5251, 0.3824, 0.8677, 0.0751, 0.2201],
        [0.7815, 0.6547, 0.1788, 0.1465, 0.1043]])

In [77]:
# we can also use tensor.reshape method to reshape tensor, it works same like view

In [78]:
tensor2

tensor([[0.5251, 0.3824, 0.8677, 0.0751, 0.2201],
        [0.7815, 0.6547, 0.1788, 0.1465, 0.1043]])

In [79]:
tensor2 = tensor2.T
tensor2

tensor([[0.5251, 0.7815],
        [0.3824, 0.6547],
        [0.8677, 0.1788],
        [0.0751, 0.1465],
        [0.2201, 0.1043]])

In [80]:
# tensor.T or torch.transpose(tensor) will make the row -> columns, columns -> row
torch.transpose(tensor2, 1, 0)

tensor([[0.5251, 0.3824, 0.8677, 0.0751, 0.2201],
        [0.7815, 0.6547, 0.1788, 0.1465, 0.1043]])

In [81]:
tensor3 = torch.rand((64, 5, 8))
tensor3

tensor([[[0.6077, 0.1247, 0.1293,  ..., 0.5227, 0.7337, 0.3966],
         [0.6031, 0.4059, 0.1158,  ..., 0.9969, 0.3695, 0.9644],
         [0.7247, 0.3420, 0.6909,  ..., 0.3139, 0.9132, 0.0208],
         [0.4132, 0.9749, 0.1676,  ..., 0.6563, 0.8833, 0.9769],
         [0.6293, 0.3563, 0.9730,  ..., 0.3227, 0.8372, 0.1112]],

        [[0.1306, 0.9922, 0.9299,  ..., 0.6345, 0.6580, 0.5016],
         [0.1303, 0.8171, 0.3591,  ..., 0.5741, 0.4390, 0.0122],
         [0.6965, 0.2764, 0.1676,  ..., 0.6469, 0.6521, 0.8824],
         [0.8001, 0.1429, 0.8315,  ..., 0.4654, 0.1588, 0.2659],
         [0.0354, 0.2889, 0.0928,  ..., 0.4421, 0.7403, 0.1121]],

        [[0.1457, 0.0532, 0.8812,  ..., 0.3527, 0.4388, 0.9839],
         [0.9208, 0.5043, 0.8733,  ..., 0.3133, 0.2440, 0.3969],
         [0.8548, 0.9716, 0.8620,  ..., 0.8121, 0.5860, 0.4073],
         [0.5281, 0.4114, 0.1823,  ..., 0.0553, 0.5280, 0.2977],
         [0.9868, 0.2370, 0.1297,  ..., 0.8163, 0.8352, 0.2665]],

        ...,

     

In [82]:
tensor3.shape

torch.Size([64, 5, 8])

In [83]:
# to switch the 1 , 2 dimension keeping 0 as smae
tensor3.view(64, -1)

tensor([[0.6077, 0.1247, 0.1293,  ..., 0.3227, 0.8372, 0.1112],
        [0.1306, 0.9922, 0.9299,  ..., 0.4421, 0.7403, 0.1121],
        [0.1457, 0.0532, 0.8812,  ..., 0.8163, 0.8352, 0.2665],
        ...,
        [0.6475, 0.6713, 0.0821,  ..., 0.0180, 0.5008, 0.1006],
        [0.3743, 0.9555, 0.4394,  ..., 0.6824, 0.2613, 0.5390],
        [0.4268, 0.6846, 0.7501,  ..., 0.0208, 0.3096, 0.4474]])

In [84]:
tensor3.shape

torch.Size([64, 5, 8])

In [85]:
tensor3 = tensor3.permute(0, 2, 1) # shifted dimensions 0 will be the same
tensor3

tensor([[[0.6077, 0.6031, 0.7247, 0.4132, 0.6293],
         [0.1247, 0.4059, 0.3420, 0.9749, 0.3563],
         [0.1293, 0.1158, 0.6909, 0.1676, 0.9730],
         ...,
         [0.5227, 0.9969, 0.3139, 0.6563, 0.3227],
         [0.7337, 0.3695, 0.9132, 0.8833, 0.8372],
         [0.3966, 0.9644, 0.0208, 0.9769, 0.1112]],

        [[0.1306, 0.1303, 0.6965, 0.8001, 0.0354],
         [0.9922, 0.8171, 0.2764, 0.1429, 0.2889],
         [0.9299, 0.3591, 0.1676, 0.8315, 0.0928],
         ...,
         [0.6345, 0.5741, 0.6469, 0.4654, 0.4421],
         [0.6580, 0.4390, 0.6521, 0.1588, 0.7403],
         [0.5016, 0.0122, 0.8824, 0.2659, 0.1121]],

        [[0.1457, 0.9208, 0.8548, 0.5281, 0.9868],
         [0.0532, 0.5043, 0.9716, 0.4114, 0.2370],
         [0.8812, 0.8733, 0.8620, 0.1823, 0.1297],
         ...,
         [0.3527, 0.3133, 0.8121, 0.0553, 0.8163],
         [0.4388, 0.2440, 0.5860, 0.5280, 0.8352],
         [0.9839, 0.3969, 0.4073, 0.2977, 0.2665]],

        ...,

        [[0.6475, 0.

In [86]:
tensor3.shape

torch.Size([64, 8, 5])

In [87]:
# to add an dimension to the tensor
tensor4 = torch.rand(10)
tensor4

tensor([0.0676, 0.7432, 0.9842, 0.0203, 0.9576, 0.8916, 0.7446, 0.5598, 0.9972,
        0.0760])

In [88]:
tensor4.shape

torch.Size([10])

In [89]:
# tensor.unsqueeze() add the dimensions to the tensor
tensor4 = tensor4.unsqueeze(1)
tensor4.shape

torch.Size([10, 1])

In [91]:
# tensor.sqeeze() remove the dimension to the tensor
tensor4 = tensor4.squeeze(1)
tensor4

tensor([0.0676, 0.7432, 0.9842, 0.0203, 0.9576, 0.8916, 0.7446, 0.5598, 0.9972,
        0.0760])

In [92]:
tensor4.shape

torch.Size([10])

In [94]:
tensor4.shape

torch.Size([10])